name: myconda
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - conda-pack=0.8.1
  - expat=2.6.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.18
  - pip=24.0
  - python=3.12.4
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==2.4.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.0.0
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - eva-decord==0.6.1
      - executing==2.0.1
      - fastjsonschema==2.21.2
      - filelock==3.15.4
      - fonttools==4.53.0
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - grpcio==1.64.1
      - h11==0.16.0
      - h5py==3.11.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hydra-core==1.3.2
      - idna==3.11
      - iopath==0.1.10
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.5
      - lark==1.3.1
      - lightgbm==4.4.0
      - llvmlite==0.46.0
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.1.7
      - mistune==3.2.0
      - mpmath==1.3.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.5.1
      - notebook-shim==0.2.4
      - numba==0.63.1
      - numpy==2.0.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.2.2
      - portalocker==3.2.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.23
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2024.1
      - pywavelets==1.9.0
      - pyyaml==6.0.3
      - pyzmq==26.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - sam-2==1.0
      - scikit-learn==1.8.0
      - scipy==1.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.16.0
      - soupsieve==2.8.1
      - spyder-kernels==2.5.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - urllib3==2.6.2
      - wcwidth==0.2.13
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.15
      - wurlitzer==3.1.1
      - yolov5==0.1.0
prefix: /home/jiaqi/anaconda3/envs/myconda
